spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: NUTRIX-NUTRITIONIST-SERVICE
          uri: lb://NUTRIX-NUTRITIONIST-SERVICE
          predicates:
            - Path=/nutritionist/**, /professional-profile/**, /specialty/**
          filters:
            - name: CircuitBreaker
              args:
                name: nutritionist-service
                fallbackuri: forward:/nutritionistFallBack
        - id: NUTRIX-PATIENT-SERVICE
          uri: lb://NUTRIX-PATIENT-SERVICE
          predicates:
            - Path=/patient/**, /bill/**, /payment-method/**
          filters:
            - name: CircuitBreaker
              args:
                name: patient-service
                fallbackuri: forward:/patientFallBack
        - id: NUTRIX-PUBLICATION-SERVICE
          uri: lb://NUTRIX-PUBLICATION-SERVICE
          predicates:
            - Path=/recommendation/**, /recipe/**
          filters:
            - name: CircuitBreaker
              args:
                name: publication-service
                fallbackuri: forward:/publicationFallBack
        - id: NUTRIX-APPOINTMENT-SERVICE
          uri: lb://NUTRIX-APPOINTMENT-SERVICE
          predicates:
            - Path=/appointment/**, /diet/**
          filters:
            - name: CircuitBreaker
              args:
                name: appointment-service
                fallbackuri: forward:/appointmentFallBack
  config:
    import:
      optional:configserver:http://localhost:9196